# https://travis-ci.org/translate/python-jproperties
sudo: false
language: python
python:
  - 3.5
script:
  - ./setup.py install
  - ./test_main.py
notifications:
  email:
    on_failure: always
    on_success: change
