# https://travis-ci.org/translate/python-jproperties
sudo: false
language: python
python: "3.6"

env:
  - TOXENV=py34
  - TOXENV=py36
  - TOXENV=flake8

cache:
  directories:
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/.tox

install:
  - pip install tox

script:
  - tox

notifications:
  email:
    on_failure: always
    on_success: change
